[package]
authors     = ["Xavier Lau <xavier@inv.cafe>"]
description = "BCP47 language tags."
edition     = "2021"
homepage    = "https://hack.ink/language"
license     = "GPL-3.0"
name        = "language"
readme      = "README.md"
repository  = "https://github.com/hack-ink/language"
version     = "0.1.2"

[profile.ci-dev]
incremental = false
inherits    = "dev"

# [profile.ci-release]
# inherits = "release"
# lto      = true

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
